parameters:

services:
    redcart_client_bridge.http_client:
        class: Guzzle\Http\Client
        arguments: ['https://api2.redcart.pl']

    redcart_client_bridge.client:
        class: RedcartClient\Api\Client
        arguments: [%redcart_api_key%]

    redcart_client_bridge.raw_to_resource_mapper:
        class: RedcartClient\Mapper\RawToResourceMapper

    redcart_client_bridge.module_locator:
        class: RedcartClient\Locator\ModuleLocator
        arguments:
          - @redcart_client_bridge.client
          - @redcart_client_bridge.raw_to_resource_mapper

    redcart_client.redcart:
        class: RedcartClient\Api\Redcart
        arguments: [["@=service('redcart_client_bridge.module_locator').getAllSupportedModules()"]]