parameters:

services:
    redcart_client_bridge.http_client:
        class: Guzzle\Http\Client
        arguments: ["@=container.hasParameter('redcart_endpoint') ? parameter('redcart_endpoint') : 'redcart_endpoint'"]

    redcart_client_bridge.client:
        class: RedcartClient\Api\Client
        arguments: ["@=container.hasParameter('redcart_api_key') ? parameter('redcart_api_key') : ''"]

    redcart_client_bridge.raw_to_resource_mapper:
        class: RedcartClient\Mapper\RawToResourceMapper

    redcart_client_bridge.module_locator:
        class: RedcartClient\Locator\ModuleLocator
        arguments:
          - @redcart_client_bridge.client
          - @redcart_client_bridge.raw_to_resource_mapper

    redcart_client.redcart:
        class: RedcartClient\Api\Redcart
        arguments: [["@=service('redcart_client_bridge.module_locator').getAllSupportedModules()"]]